services:
  nde-devenv:
    build: 
      context: .
      dockerfile: Dockerfile
    init: true
    privileged: true  
    command: sleep infinity    
    
    volumes:
    - ../.devcontainer:/app/.devcontainer
    - ../:/app
    - docker-data:/var/lib/docker

volumes:
  docker-data:
